name: build ci container

on:
  push:
    branches:
      - 'master'
      - 'container'
    paths:
      - '.github/workflows/container.yml'
      - 'test/Dockerfile'
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install QEMU
      run: |
        sudo apt-get update
        DEBIAN_FRONTEND='noninteractive' sudo apt-get install -qy qemu-user-static
    # remove this when Ubuntu 24.04 is available on GitHub Actions
    - name: Enable Ubuntu noble and update buildah
      run: |
        echo 'deb http://archive.ubuntu.com/ubuntu/ noble main restricted universe' | sudo tee -a /etc/apt/sources.list.d/lunar.list
        echo 'deb http://archive.ubuntu.com/ubuntu/ noble-updates main restricted universe' | sudo tee -a /etc/apt/sources.list.d/lunar.list
        sudo apt-get update
        DEBIAN_FRONTEND='noninteractive' sudo apt-get install -qy buildah
        buildah version
    - uses: actions/checkout@v3
    - name: Build Images
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: rauc-ci
        tags: latest
        platforms: linux/amd64, linux/386, linux/arm/v5, linux/arm/v7, linux/arm64/v8
        dockerfiles: |
          ./test/Dockerfile
    - name: Echo Outputs for Build
      run: |
        echo "Image: ${{ steps.build-image.outputs.image }}"
        echo "Tags: ${{ steps.build-image.outputs.tags }}"
        echo "Tagged Image: ${{ steps.build-image.outputs.image-with-tag }}"
    - name: Push Images
      id: push-to-github
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-image.outputs.image }}
        tags: ${{ steps.build-image.outputs.tags }}
        registry: ghcr.io/${{ github.repository }}
        username: ${{ github.actor }}
        password: ${{ github.token }}
    - name: Echo Output for Push
      run: echo "Image pushed to ${{ steps.push-to-github.outputs.registry-paths }}"
